import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import MainNav from "@/components/MainNav";
import { ThemeProvider } from "next-themes";
import { SessionProvider } from "next-auth/react"
import Providers from "./LayoutProviders";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Ticket Application",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <Providers>
          <nav className="flex flex-col items-center border-b mb-5 px-5 py-3">
              <div className="max-w-6xl w-full">
                <MainNav />
              </div>
            </nav>
              <main className="flex flex-col items-center">
                  <div className="max-w-6xl w-full">
                    {children}
                  </div>
              </main>
        </Providers>
      </body>
    </html>
  );
}
